### PR TITLE
Some client side input validation #85

### PR DESCRIPTION
**Pull request by Tuvyu**
Hi, this is my first time doing a pull request, so, I apologize beforehand if I made any mistake. So, today, I noticed an open issue which was #85 and attempted to remedy it as much as possible. 

I use Windows 10. And I have tested it out on Chrome, Firefox, Brave, and Opera Gx.
Except for Firefox, rest block the user from inputting any letters except the letter 'e'. And they all have been tested for negatives, floats, and seemed to do fine. There is a minimum of 5000 for both height and width.

Lastly, these are all on the client side and not server verified.

### CODE REVIEW

**Comment by Tuvyu** [comment]
Hi

Thanks for the detailed response. I appreciate it. I will do as you say!

**Comment by Tuvyu** [comment]
Hello

I have made the changes. Placed numberValidator into Util.js, created four class properties in Filejs to keep track of incorrect inputs and prevent resizing accordingly. I have done some shallow testing and they seem to work.

Can you please take a look first? I will work on the custom range afterward.

Thank you!

**Comment by unsettledgames** [comment]
Thanks! The "Keep current ratio" button in the scale sprite window doesn't seem to be working anymore for some reason. The rest seems to be ok, maybe reset the window parameters when a bad one is inserted so that the user has a minimum amount of feedback :)

**Comment by Tuvyu** [comment]
Yes, I was thinking of that and I even added a warning injection at first but I kept encountering some issues so I removed them while also considering I should not unnecessarily add things. But with your confirmation, I can work on it more flexibly now!

I will also check out the issue you mentioned.

**Comment by unsettledgames** [comment]
A simple warning div or maybe even an alert should be enough if you want to notify the user, that would be great if you have time, otherwise no problem and you can just reset the parameters

**Comment by Tuvyu** [comment]
That's exactly what I had at first. I will retry building it out again as I understand the states more now. Last time, it kept memory leaking but it was also cause I did not have a proper validation structure.

**Comment by Tuvyu** [comment]
Hi
The "Keep current ratio" does not seem to be working in the prod app too. It resets to 100% every time. I am unsure if you were talking about that.

**Comment by Tuvyu** [comment]
Hello

I have made the changes and added a span feedback. I will look into the 'keep current ratio' issue moving forward but can you please look at this first?

Thank you

**Comment by Tuvyu** [comment]
Hello

I think I fixed 'keep current ratio'. Can you confirm? Thanks.

**Comment by unsettledgames** [comment]
Almost there, if "keep ratio" is enabled, the same effect should be applied also when the "New sizes" fields are edited, not only the percentages

**Comment by Tuvyu** [comment]
I figured so. Okay, will work on it in a bit!

**Comment by Tuvyu** [comment]
Wait, I don't understand. I don't see the problem. Can you clarify?

**Comment by Tuvyu** [comment]
Hello

I need more clarification cause it looks alright to me. Thanks.

**Comment by Tuvyu** [comment]
No worries. I also started a software developer internship a few days ago.  I will take a look at this when I have time!

**Comment by Tuvyu** [comment]
It should be fixed now. I had some class properties, sh and sw from some previous attempts that I forgot to remove which was causing the issue. It's resolved now. Please take a look!

**Comment by Tuvyu** [comment]
bump!

**Comment by unsettledgames** [comment]
If you disable the "Keep ratio" button, edit the fields, re-enable the "Keep ratio" button and edit the fields, the button doesn't work. Example:
- Set width percentage to 200%, all fields update correctly
- Disable "Keep ratio"
- Halve the width value
- Enable the "Keep ratio" button
- Double the height percentage
- 
Correct behaviour: the other fields update as well
Observed behaviour: only the height percentage field updates

Please, try making a more thorough testing before submitting for review

**Comment by Tuvyu** [comment]
I think I can see some consistent issues. But I feel like it will take me too long to figure this out.  So, I do not plan to work on it anymore. If there is anything else, I can work on, I can. Otherwise, you can archive this issue and I can move on.

Thanks!

**Comment by unsettledgames** [comment]
I'll close this one then. Unfortunately, I don't see any other issues that could be easier to tackle than this one. Feel free to reopen it if you feel like it in the future, thanks anyways for the effort

**Pull request closed without merging**
