### PR TITLE
Snap brush preview to pixel grid to prevent incoherences between preview and drawing

### PR DESCRIPTION
**Pull request by Lattay**
Hello,
I modified the `draw` function from `js/_mouseEvents.js` snap brush preview to the pixel grid and thus make it coherent with the drawing.

I also made some more opiniated formal modifications to stick to a coherent style guide (see `.eslintrc.json\ and `js/.eslintrc.json`) and modified the build script to use gulp for all steps (thus allowing for parallel build).

As those changes are quite opiniated I could understand that it is not wanted upstream, but I think the brushPreview change was much needed (using pencil of size 4 on a 16 by 16 canvas show the problem). As a consequence, if you want I could do a pull request with only this particular change.

What do you think ?

PS: By the way I would really be interested in continuing improving this code, I was looking at the idea of starting such a project, but this one have all the basics and is ready to become great.

### CODE REVIEW

**Comment by lospec** [comment]
Hi @Lattay ! Thanks for your contribution! I am currently working with @unsettledgames to get his pull request added, but will add yours right after! The changes seem fine to me.

We would love to have more contributions to the project. We discussing maybe starting some docs to make it easier for people to contribute. I know the code could be organized a little better, I would love for tools to be more modular so everything can be contained in one file, plus all the things listed on the readme really need to be done, but I don't have the time to work on the editor as I'm working on other Lospec features. I would love for this to become a more usable and advanced editor. If you want to chat about it in depth feel free to message me on discord (skeddles#7463, or you can join our channel), or message me anywhere else!

**Comment by Lattay** [comment]
I think some more structural changes could help in adding new features.
For example it could be a good idea to move to ES6 [modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules) instead of old style scripts to provide linters with more grasp of what's going on and thus detecting bugs earlier. You could eventually add [Babel](https://babeljs.io/) to the build process to use modern JS features while keeping wide compatibility with older or simpler browsers.
Another good think to do would be to remove as much global variables as possible, they could create hard to track bugs so easily.

**Comment by lospec** [comment]
Would you mind removing the part that applied the eslint (or redo it)? I like the feature but it's causing a conflict now that I merged the other pull request and I can't figure out how to solve the conflicts. Thanks

**Comment by Lattay** [comment]
Hi, I fixed the conflict and applied the brush snapping t the rectangle tool. Also I fix the pencil size button that were broken in your master branch because of the brushSize -> pencilSize change.

**Pull request merged**
