### PR TITLE
Implement importing GIMP and .hex palettes.

### PR DESCRIPTION
**Pull request by Lattay**
Hi,
I would like to propose a new feature palette loading dialog.
I extended the dialog handler to support .gpl (GIMP palettes) and .hex such as the ones exported from the [palette list](https://lospec.com/palette-list).
In both formats I support comments starting with `#` too.

### CODE REVIEW

**Review by unsettledgames — CHANGES_REQUESTED** [review]
Can you please group the importing code for each format into their own format to keep things a bit more tidy?

**Comment by unsettledgames** [comment]
Heyo! Thanks a lot for the PR and for your time. This is definitely a useful feature and the code looks nice at the moment. I just added a small comment, I'd like to have the code for the importing grouped into separate functions just to keep things a bit tidier. Being able to import a palette from a File->Import palette button would also be nice.

**Comment by Lattay** [comment]
Here is the refactoring. Is it ok for you ?

**Comment by Lattay** [comment]
Sorry, I am not sure how to use the review features...

**Comment by unsettledgames** [comment]
Hey thanks for the refactoring! It does look better now. I'm assuming you still have to add a way for the user to load a palette unless I'm missing something? A button in the file menu would be nice.

**Comment by Lattay** [comment]
For the loading of a palette from the menu I am not sure how to do it, because here I just hacked on the existing system, but I am not sure how easy it would be to use it directly. I think it should be a separate PR anyway. What do you think ?

**Comment by unsettledgames** [comment]
I'd prefer it to be included in the same PR, in that way it would make an entire, working new feature. If you have time and you want to implement that, the relevant files are:

- https://github.com/lospec/pixel-editor/blob/master/views/main-menu.hbs (top menu html)
- https://github.com/lospec/pixel-editor/blob/master/js/TopMenuModule.js (mostly from line 36) for binding the function

You can follow the flow of the second file to understand how to integrate your feature with the rest, it shouldn't be too hard but if you have any questions feel free to ask here :)

Otherwise, I can take care of that, contribute to your PR and then merge it.

**Comment by Lattay** [comment]
Ok, I will have a look in the next few days. If I don't feel I can do I'll tell you.

**Comment by Lattay** [comment]
Ok, it's a bit hacky in how I reused existing components, but it works well, and I avoided doing actual UI work (I am not good at that).
I chose to extend the existing palette rather than replacing it because it feels more tedious to merge palettes when you replace automatically than to manually clear the previous palette when you automatically extend.

**Comment by unsettledgames** [comment]
Hey! It is indeed a little hacky, but it's a nice feature to have and it'd be pretty easy to fix it in the future if we want to. Overall really nice job, I'm merging this. Thanks a lot for your time and for contributing!

**Pull request merged**
