### PR TITLE
Added file option to import image to current layer

### PR DESCRIPTION
**Pull request by NSSure**
Basic implementation is here. there is functionality that can be expanded if necessary. Nothing was done for determining where in the layer the image is imported or modifying the palette based on image colors.

### CODE REVIEW

**Comment by unsettledgames** [comment]
Thanks a lot for the contribution, the basic behaviour seems to be working correctly! At the moment it would be nice to place the image at the center of the canvas instead of using its top left corner as a pivot. In the future we could generalize and recycle the code for canvas resizing to specify a custom pivot point.

It would be nice to add a checkbox to add the image colors to the palette if you feel like adding that (similar to what you've done to resize the canvas when importing). Otherwise I can probably find some time to do that.

Just a little bug, if you try to import multiple images (one after another), the dialog box is opened twice, probably related to #101

**Comment by NSSure** [comment]
@unsettledgames I have some time so I can take care of those three issues. One point of clarification on the bug you mention, Is that referring to the "Import image" window or the error popup when attempting to import before selecting an image? I can re-create the error popup multiple times but not the actual "Import image" window.

**Comment by unsettledgames** [comment]
> @unsettledgames I have some time so I can take care of those three issues. One point of clarification on the bug you mention, Is that referring to the "Import image" window or the error popup when attempting to import before selecting an image? I can re-create the error popup multiple times but not the actual "Import image" window.

@NSSure thanks a lot! Regarding the bug, here are the steps to reproduce it and the effects:
- Import correctly an image in the editor
- Try importing another image
- After selecting the file in the file explorer, another file explorer is opened and the previous selection is discarded

So, the "Import Image" isn't duplicated, but the file explorer is opened twice. If an error occurs during the file selection, the error popup also appears twice.

**Comment by NSSure** [comment]
@unsettledgames Those three issues have been resolved. A workaround was added for the multiple file explorer instances using a flag to track if the window is initialized. That issue is related #101 and should probably be handled in a more structured manner in the future.

**Comment by unsettledgames** [comment]
@NSSure lovely work, thanks a lot for the contribution! I'm merging it, hopefully I'll find some time to fix #101 .

**Pull request merged**
