### PR TITLE
Fixed removal of all the colors from palette

### PR DESCRIPTION
**Pull request by amritrai5757**

### CODE REVIEW

**Comment by unsettledgames** [comment]
Thanks for the PR! The code right now feels a bit redundant. Can't you just subtract one from endIndex if the user is trying to remove all the colours?

**Comment by amritrai5757** [comment]
Okay

**Comment by amritrai5757** [comment]
I have made the changes. Please look at it. If there any problem from my side, please tell me. I'll make sure to fix it.

**Comment by unsettledgames** [comment]
Hey, thanks for the attempt. I may not have properly explained myself, what I meant is, if the user is trying to delete all the colours, delete ALL of them except the last one. To do so, it's probably enough to keep the old code, check when the user is trying to delete all the colours and decrease endIndex by 1.

**Comment by unsettledgames** [comment]
Looking perfect, I'm merging this! Thanks 👍

**Comment by amritrai5757** [comment]
Thanks 👍👍

**Pull request merged**
