### PR TITLE
Add devcontainer for easy development setup

### PR DESCRIPTION
**Pull request by amritrai5757**
Added devcontainer folder so that whoever is going to contribute using github codespace, they did not have to setup whole development setup, they will just run "npm run hot" & it will start running.

### CODE REVIEW

**Comment by amritrai5757** [comment]
Please review @unsettledgames

**Comment by unsettledgames** [comment]
How does this work? I cloned the repo, ran 'npm run hot' but it didn't work, complained about concurrently not being loaded.

**Comment by amritrai5757** [comment]
First fork the repo, then select the "main" branch in the forked repo & then click on "code" & then on "codespace" , select  "create codespace on main" .
Wait for codespace to be built, & then a vscode appears on website.Wait for 1-2 minutes till you see npm install running in terminal & port built automatically. After that simply type "npm run hot" to start.

**Comment by amritrai5757** [comment]
It is all cloud based, so need to install node locally & setup environment to run the project

**Comment by unsettledgames** [comment]
That's really cool! Sorry for the noob questions but I don't know much about this kind of stuff. Merging, thanks a lot!

**Pull request merged**
