### PR TITLE
Added export dialogue

### PR DESCRIPTION
**Pull request by NSSure**
Added an export dialogue that allows for the file name to be customized. The file name input uses the previous name generated
using the selected palette and canvas size.

### CODE REVIEW

**Comment by unsettledgames** [comment]
Hello, thank you so much for the contribution! We'd love to merge this, but before doing that could you please solve this issue?
https://imgur.com/qIKWJBY
Apparently, when the name of the file is blank, it almost looks like there's some hidden text that gets shown. Another thing we'd like to have before merging is a similar window, but for saving the project as a .lpe file (the Save button).

Looking forward to hearing back from you!

**Comment by NSSure** [comment]
@unsettledgames So I took a quick look and the empty text issue and I can't seem to reprouduce that. Are there any specific steps I should be taking to reproduce the issue?

I can add another dialogue for the project save process. I assume the name for the .lpe file would be one dialogue options. Are there any other configurable options that would be needed for save project dialogue?

**Comment by unsettledgames** [comment]
@NSSure I'm using Edge, version 92.0.902.67. To reproduce, use CTRL+A to select all the text and CTRL+X to cut it: this will create the artifacts in the pic I linked above. If you're not able to reproduce it or if it takes you too much time to fix it, don't worry about it, it's a very minor issue. About the save project window, you can just use a filename textbox for now. 

I was also thinking that it'd be great if you could find some way to let the user choose the location in which they want to save the pixel, but if you don't have time we can do that in another pull request. 

Let me know if you need anything else!

**Comment by NSSure** [comment]
@unsettledgames I didn't fix the text artifacts issues since I am still unable to reproduce using Edge version 92.0.902.67.

I committed the save project dialogue with the option to set the name of the .lpe file. As for the user selecting the file location the user can control that using a browser setting that they can have the browser prompt them for a file location on file downloads.

However there are a few alternatives, but I didn't go ahead and add them since not all browsers support the specific browser working draft standard we would need specifically https://developer.mozilla.org/en-US/docs/Web/API/Window/showSaveFilePicker. It would be straightforward to implements this for the specific supporting browsers but I was not sure on the stance of using such standards.

**Comment by unsettledgames** [comment]
Thanks for the new commits! Well, if it's a browser preference I'd avoid bypassing it.

I'll merge the request as it looks like it's working fine, if you want to contribute again in the future, please consider joining the Lospec Discord server (https://discord.com/invite/QjsgTQM) and ping @skeddles asking for the Dev role to gain access to a few channels where me and other contributors usually talk about the editor.

Have a nice day :)

**Pull request merged**
