### PR TITLE
Limited canvas size to 5000x5000

### PR DESCRIPTION
**Pull request by SIrizarry**
Also added a div with a simple message detailing the limit that appears once a user has hit the limit

### CODE REVIEW

**Comment by unsettledgames** [comment]
Hi and thanks for the contribution! It seems to be working but it's a bit unreliable. For example, I can still input negative numbers and alphabetic characters; also, with a fast click it's still possible to create a huge canvas before the value autoupdates in the input field.

 I think this issue should be solved by setting the right attributes of the input fields (such as `min`, `max `and `type`). In addition, the same modifications should be made to the canvas resize and sprite scaling dialogues, which can also be used to change the size of the canvas. It shouldn't be too hard to tackle, let me know if you have time to do that.

**Comment by SIrizarry** [comment]
Thanks for taking a look! I get you mean and I think you'll approve of how it works now for the splash page and the file > new popup. I have no problem changing the canvas resize and sprite scaling dialogue inputs as well.

**Comment by unsettledgames** [comment]
Thanks! Almost there, I can still input negative numbers and create huge canvases via the sprite scaling dialogue. Checking the computed values should be enough to fix that :)

Also, maybe the canvas limit should be around 3000x3000, which still causes some lag but could be reasonable. I also think that the max canvas size should be declared in consts.js (https://github.com/lospec/pixel-editor/blob/master/js/data/consts.js) so that we have less literals around.

image

**Comment by SIrizarry** [comment]
Hiya, I think i've addressed everything you mentioned with the last two commits. Please let me know if I've broken anything or done something horrible, thanks! 🤞

**Comment by unsettledgames** [comment]
Hey! It's almost all fine, thanks a lot for your time. Nothing horrible, but I think the sprite scaling is a bit broken now: it looks like the percentage fields, instead of being treated as such, are used to directly set the size. For example:

- Create a new 128x128 sprite
- Open the scale sprite dialogue, set 200% for both width and height
- Expected result: the sprite gets scaled to 256x256
- Actual result: the sprite is now 200x200

In addition, the checkbox to keep the current canvas ratio seems to be ignored.

**Comment by SIrizarry** [comment]
No problem! Thanks for checking these even though my own personal QA has fallen so far as be considered completely absent 😭 Btw, how exactly is the canvas ratio checkbox supposed to work. Should it match both canvas ratios or say, if width is at 50% and height at 100% if width goes to 25% then should height go to 50%?

**Comment by unsettledgames** [comment]
Hey no worries at all! It's hard to find all the bugs in one go :)

The ratio button, when enabled, should work in both ways you mentioned:
- Percentages are kept identical
- The width / height ratio of the output should be the same of the input

You may also have noticed that when width / height are updated, so are the percentages and viceversa.

**Comment by unsettledgames** [comment]
Closed for inactivity

**Pull request closed without merging**
